### ISSUE TITLE
BUG: I sent a NFT 2 times with same command and got success both times.

### ISSUE THREAD

**Issue by uniqlabsorg** [game-of-nfts/gon-evidence#323]
## Summary of Bug

For b1-revisit task, I sent a NFT from uptick to stargaze 2 times and got success both times.

## Environment

- OS: Any
- Software version: Any

## Steps to Reproduce

1. I created a NFT with "uniqnft12" id under "uniq1" collection in iris.
   (AFDD2A01A37ECDCB9208F690C113C35C53FAB63A8EA5787AA18D488C8C135760)
2. I sent this NFT from iris to stargaze.
   (F7AA5E1383EDADB499D46CDDDBE8896E5C71074C83E719F50FDAA478D7973E5E)
3. I sent this NFT from stargaze to uptick.
   (B6516650259E798921F73A843FB4AB505B6D737120AB1FE040701C30F34020E9)
4. I sent this NFT from uptick to stargaze and got success, but when I couldn't see the NFT on stargaze, I sent it again with the same command and got success again.
(D8466750AFA1ED29FB2AE19F893627343FAE221553B3B4ACD539FA91B2332EDF)
(E2E238AD26E76CB17694C885C55EFFA04887C5D156D641091321C1489DC52101)

## Expected and Actual Behavior

The submission should have failed and I should have gotten the following error.
"failed to execute message; message index: 0: not token owner: unauthorized"

But both submissions were successful.
**Uptick Tx-1: D8466750AFA1ED29FB2AE19F893627343FAE221553B3B4ACD539FA91B2332EDF**
         _2023-03-07 05:35_
**Uptick Tx-2: E2E238AD26E76CB17694C885C55EFFA04887C5D156D641091321C1489DC52101**
         _2023-03-07 18:11_

## Error Stack

-

## Additional Context

-

**Comment by giansalex** [comment]
The IBC proccess ended with a timeout, because wrong timeout-height [3700652](https://gon.ping.pub/stargaze/blocks/3700652)

IBC-Transfer: https://explorer.testnet.uptick.network/uptick-network-testnet/tx/D8466750AFA1ED29FB2AE19F893627343FAE221553B3B4ACD539FA91B2332EDF

IBC Timeout: https://explorer.testnet.uptick.network/uptick-network-testnet/tx/E1EC2793B20B5CB440EFA21774263658ABE1C2AC1AC64A9D129028E3FA287433

these confusions would be avoided with a explorer like Mintscan.
